config/routes.rb
LrMediaroom::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get '/ricerca' => 'photos#search', :as => 'search'
  get '/accedi' => 'sessions#new', :as => 'new_session'
  post '/accedi' => 'sessions#create', :as => 'create_session'
  get  '/esci' => 'sessions#destroy', :as => 'destroy_session'
  resources :videos, :only => [:index] do
    member do
      get '/download' => 'videos#download', :as => 'download_attachment'
    end
  end
  resources :galleries, :only => :index do
    resources :photos, :only => [:index, :show] do
      get 'download-originale' => 'photos#download', :on => :member, :as => 'download'
    end
  end
  root :to => 'galleries#index'
  match "/signup" => redirect("http://eepurl.com/kvmXv"), :as => :signup

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/gallery.rb
require 'tools/photo_extractor'

class Gallery < ActiveRecord::Base

  UPLOAD_FOLDER = File.join(Rails.root, 'galleries')

  has_many :photos, :dependent => :destroy

  scope :published, where(:published => true)
  default_scope :order => "gallery_date DESC"

  def self.uploaded_files
    @uploaded_files ||= []
    if @uploaded_files.empty?
      Dir[File.join(UPLOAD_FOLDER, '**', '**.*')].each do |file|
        @uploaded_files << file.gsub("#{UPLOAD_FOLDER}/", '')
      end
    end
    return @uploaded_files
  end

  def self.import_from_archive(path)
    ActiveRecord::Base.transaction do
      images = Tools::PhotoExtractor.extract(path)
      gallery = self.create :title => "#{Date.today} Gallery"
      images.each do |image|
        gallery.photos << Photo.import_from_path(image)
      end
      return gallery
    end
  end

  def cover
    gallery_photos = self.photos.published
    return gallery_photos.cover.first || gallery_photos.first
  end
end

app/models/photo.rb
# encoding: UTF-8
require 'mini_exiftool'

class Photo < ActiveRecord::Base
  belongs_to :gallery

  scope :published, where(:published => true)
  scope :recent, order('id DESC').limit(5)
  scope :cover, where(:cover => true).order('id DESC').limit(1)

  mount_uploader :image, ::PhotoUploader

  def self.import_from_path(path)
    file_data = MiniExiftool.new path, :convert_encoding => true
    data = {
      :description => (file_data.description || file_data.file_name).encode('utf-8'),
      :city => file_data.city.try(:encode, 'utf-8'),
      :country => file_data.country(:encode, 'utf-8'),
      :image => File.open(path),
      :published => true
    }
    image = Photo.new data
    if image.save
      return image
    else
      return false
    end
  end

  def next
    self.gallery.photos.where("id > ?", self.id).order('id ASC').first
  end

  def prev
    self.gallery.photos.where("id < ?", self.id).order('id DESC').first
  end
  
  protected
end

app/models/user.rb
class User
  include ActiveModel::AttributeMethods
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :email

  LISTS = ["50dbfac20c"]
  MAILCHIMP_API_KEY = 'e9bfe9fb82eeba0fd75c7e012e33f859-us4'

  
  def self.authenticate(email)
    mailchimp = Gibbon.new(MAILCHIMP_API_KEY)
    LISTS.each do |list|
      user_info = mailchimp.listMemberInfo :id => list, :email_address => email
      return self.new(:email => email) if user_info['success'] == 1
    end
    return nil
  end

  def initialize(params = {})
    self.email = params[:email]
  end

  def persisted?
    false
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  
  UPLOAD_FOLDER = File.join(Rails.root, 'videos')

  mount_uploader :cover, VideoCoverUploader
  
  scope :published, where(:published => true)
  scope :recent, order('id DESC').limit(5)
  
  def self.uploaded_files
    @uploaded_files ||= []
    if @uploaded_files.empty?
      Dir[File.join(UPLOAD_FOLDER, '**', '**.*')].each do |file|
        @uploaded_files << file.gsub("#{UPLOAD_FOLDER}/", '')
      end
    end
    return @uploaded_files
  end

  def method_missing(method_name, *args)
    if method_name =~ /^(attachment_[1-9])_path$/ and self.respond_to? $1
      return File.join(UPLOAD_FOLDER, self.send($1))
    end
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.new(:email => session[:user]) if session[:user]
  end

  def require_authentication
    if current_user.nil?
      if params[:gallery_id].present? and params[:id].present? # voglio scaricare una foto
        session[:return_to] = gallery_photo_path(params[:gallery_id], params[:id])
      else
        session[:return_to] = request.url
      end
      redirect_to new_session_path, :alert => 'To view this content you have to login'
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
  	@galleries = Gallery.published
                        .page(params[:page]).per(20)
  end

  def show
    @gallery = Gallery.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #before_filter :require_authentication, :only => [:download]
  def index 
    @gallery = Gallery.find(params[:gallery_id])
    @photos = @gallery.photos
                      .published
                      .order('id ASC')
                      .page(params[:page]).per(20)
  end

  def search
    @photos = Photo.search_by_description(params[:q])
                   .page(params[:page]).per(20)
  end

  def show
    @gallery = Gallery.find(params[:gallery_id])
    @photo = @gallery.photos.find(params[:id])
  end

  def download
    @gallery = Gallery.find(params[:gallery_id])
    @photo = @gallery.photos.find(params[:id])
    send_file @photo.image.path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email])
    if user
      session[:user] = user.email
      redirect_path = session.delete(:return_to) || root_path
      redirect_to redirect_path, :notice => 'Logged in!'
    else
      flash.now.alert = 'The provided email address is not in our database'
      render :new
    end
  end

  def destroy
    session[:user] = nil
    redirect_to root_path, :notice => 'Logout succesfully'
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #before_filter :require_authentication
  def index
    @videos  = Video.published.order("video_date DESC")
                    .page(params[:page]).per(20)
  end

  def download
    attachment = "attachment_#{params[:attachment]}_path".to_sym
    puts  attachment
    video = Video.published.find params[:id]
    begin
      send_file video.send(attachment).gsub(/releases\/[0-9]+/, 'shared')
      return
    rescue
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/galleries/upload.html.erb
<%= form_tag :controller => 'admin/galleries', :action => :import do %>
  <fieldset class="inputs">
    <ol>
      <li class="string input optional">
        <%= label_tag :path %>
        <%= select_tag :archive_name, options_for_select(Dir.glob("galleries/**/*").map{|e| e.gsub("galleries/","")}) %>
      </li>
    </ol>
  </fieldset>
  <fieldset class="buttons">
    <ol>
      <li class="commit button">
        <input class="create" id="gallery_submit" name="commit" type="submit" value="Upload Gallery">
      </li>
      <li class="cancel">
        <%= link_to 'Cancella', admin_galleries_path %>
      </li>
    </ol>
  </fieldset>
<% end %>

app/views/admin/photos/_form.html.erb
<%= semantic_form_for [:admin, @photo], :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :gallery %>
    <%= f.input :description %>
    <%= f.input :city %>
    <%= f.input :country, :as => :string %>
    <% if @photo.image.present? %>
      <%= image_tag @photo.image.url(:thumb) %>
    <% end %>
    <%= f.input :image %>
    <%= f.input :published %>
    <%= f.input :cover %>
    <%= f.buttons %>
  <% end %>
<% end %>

app/views/admin/videos/_form.html.erb
<%= semantic_form_for [:admin, @video], :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :description %>
    <%= f.input :city %>
    <%= f.input :video_date %>
    <%= f.input :country, :as => :string %>
    <% if @video.cover.present? %>
      <%= image_tag @video.cover.url %>
    <% end %>
    <%= f.input :cover %>
    <% 2.times do |i| %>
      <%= f.input "attachment_#{i+1}_label".to_sym %>
      <%= f.input "attachment_#{i+1}".to_sym, :as => :select, :collection => Video.uploaded_files %>
    <% end %>
    <%= f.input :published %>
    <%= f.buttons %>
  <% end %>
<% end %>

app/views/galleries/index.html.erb
<div class="page-header">
  <h1>Photo Galleries</h1>
</div>
<ul class="main-grid">
  <% @galleries.each do |gallery| %>
    <li class="col">
    <div class="col_element">
      <div class="col_image">
      <% if gallery.cover.present? %>
      <%= link_to (image_tag gallery.cover.image.url(:preview), :alt => gallery.title), gallery_photos_path(gallery) %>
      <% end %>
    </div>
      <div class="caption">
        <%= content_tag :p, gallery.gallery_date.strftime("%m/%d/%Y") %>
        <%= content_tag :h5, gallery.title %>
        <%= content_tag :p, gallery.description %>
        <p><%= link_to 'View', gallery_photos_path(gallery), :class => "btn btn-danger" %></p>
      </div>
    </div>
    </li>
  <% end %>
</ul>
<%= paginate @galleries %>

app/views/galleries/show.html.erb
  <div class="hero-unit">
    <%= content_tag :p, @gallery.gallery_date %>
    <%= content_tag :h1, @gallery.title %>
    <%= content_tag :p, @gallery.description %>
  </div>
  <ul class="thumbnails">
    <% @gallery.photos.each do |photo| %>
      <li class="span3">
      <div class="thumbnail">
        <%= image_tag photo.image.url(:preview), :alt => photo.description %>
        <div class="caption">
          <%= content_tag :h5, photo.description %>
          <%= content_tag :p, "#{photo.city} - #{photo.country}" %>
          <p><%= link_to 'Visualizza', gallery_photos_path(@gallery), :class => "btn btn-danger" %></p>
        </div>
      </div>
      </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
<head>
  <title>Luna Rossa Media Room</title>
  <link href="https://stackpath.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css" rel="stylesheet" integrity="sha384-EAs/2xIodeYnc03rJToARHvNHFcPHv+Gndif5gelxOUVUM440UC9/rJdovM84FlL" crossorigin="anonymous">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
<% if flash[:notice].present? %>
  <div class="alert alert-success">
    <h4 class="alert-heading"><%= flash[:notice] %></h4>
  </div>
<% end %>

<div class="page-header">
  <h1><img src="/logolr.png"></h1>
</div>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <%= link_to "Media Room", root_path, :class => 'brand' %>
        <ul class="nav">
          <li class="<%= 'active' if controller.controller_name =~ /^galleries|photos$/ %>">
            <%= link_to 'Photos', galleries_path %>
          </li>
          <li class="<%= 'active' if controller.controller_name =~ /^videos$/ %>">
            <%= link_to 'Videos', videos_path %>
          </li>
        </ul>
        <%= form_tag search_path,:method => :get, :class => 'navbar-search pull-left' do %>
          <%= text_field_tag 'q', nil, :class => 'search-query', :placeholder => 'Search' %>
        <% end %>
        <ul class="nav pull-right">
          <% if current_user %>
            <li class="welcome"><p>Welcome <%= current_user.email %></p></li>
            <li class="divider-vertical"></li>
            <li><%= link_to 'Exit', destroy_session_path %></li>
          <% else %>
            <li><%= link_to 'Login', new_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

<%= yield %>
<footer class="footer">
  <p>© Copyright Luna Rossa Challenge 2013 srl - P. IVA 01500090533 | <a href="mailto:press.office@lunarossachallenge.com">CONTACT PRESS</a></p>
</footer>
</div>
</body>
</html>

app/views/photos/_list.html.erb
<ul class="main-grid">
  <% photos.each do |photo| %>
     <li class="col">
    <div class="col_element">
      <div class="col_image">
      <%= link_to (image_tag photo.image.url(:preview), :alt => photo.description), gallery_photo_path(photo.gallery_id, photo) %>
    </div>
      <div class="caption">
        <%= content_tag :h5, photo.description %>
        <%= content_tag :p, "#{photo.city} - #{photo.country}" %>
        <p><%= link_to 'Open', gallery_photo_path(photo.gallery_id, photo), :class => "btn btn-danger" %></p>
      </div>
    </div>
    </li>
  <% end %>
</ul>
<%= paginate photos, :theme => 'application' %>

app/views/photos/index.html.erb
<div class="page-header">
  <%= content_tag :h1, @gallery.title %>
  <%= content_tag :p, @gallery.gallery_date %>
  <%=simple_format content_tag :p, @gallery.description %>
</div>
<%= render :partial => 'list', :locals => { :photos => @photos } %>

app/views/photos/search.html.erb
  <div class="page-header">
    <h1>Risultati della ricerca</h1>
    <p>Hai cercato: <%= params[:q] %></p>
  </div>
  <%= render :partial => 'list', :locals => { :photos => @photos } %>

app/views/photos/show.html.erb
<div class="page-header">
  <%= content_tag :h2, @gallery.title %>
</div>

<ul class="nav nav-pills">
  <%= content_tag :li, (link_to 'Prev', gallery_photo_path(@gallery.id, @photo.prev.id)) if @photo.prev.present? %>
  <%= content_tag :li, (link_to 'Next', gallery_photo_path(@gallery.id, @photo.next.id)) if @photo.next.present? %>
</ul>

<div class="row-fluid" style="margin-top:5px">
  <div class="span12">
    <%= image_tag @photo.image.url(:big) %>
  </div>
</div>
<%= content_tag :p, @photo.description %>
<%= content_tag :p, "Shot in #{@photo.city} (#{@photo.country})" %>
<%= content_tag :p, link_to('Download full size', @photo.image.url, :class => 'btn btn-danger btn-large', :target => '_blank') %>

app/views/videos/index.html.erb
<div class="page-header">
  <h1>Videos</h1>
</div>
<ul class="main-grid">
  <% @videos.each do |video| %>
    <li class="col">
    <div class="col_element">
      <div class="img_cont">
      <%= image_tag video.cover.url, :alt => video.description %>
    </div>
      <div class="caption">
        <%= content_tag :h5, video.description %>
        <%= content_tag :p, "#{video.city} - #{video.country}" %>
        <% 2.times do |i|%>
          <p><%= link_to video.send("attachment_#{i+1}_label"), ("/videos/" + video.send("attachment_#{i+1}")), :class => "btn btn-danger" if video.send("attachment_#{i+1}").present? %></p>
        <% end %>
      </div>
    </div>
    </li>
  <% end %>
</ul>

<%= paginate @videos, :theme => 'application' %>